package com.menfis.delivery.domain;

public enum OrderStatus {
  CREATED,
  PAYMENT_REQUESTED,
  PAYMENT_PENDING,
  PAYMENT_PROOF_PENDING,
  PAYMENT_APPROVED,
  PAID,
  ACCEPTED,
  IN_PREPARATION,
  READY,
  PICKED_UP,
  OUT_FOR_DELIVERY,
  DELIVERED,
  CANCELLED
}
