import { MenuItem } from "./types";
import burgerPhoto from "@/imports/image-9.png";
import friesPhoto from "@/imports/image-20.png";

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "burger",
    name: "Menfi's Burger",
    eyebrow: "Clássico da casa",
    desc: "Brioche dourado, burger suculento, queijo derretido, cebola caramelizada e a maionese Menfi's.",
    price: 21.9,
    originalPrice: 26.9,
    image: burgerPhoto,
    tags: ["100g", "Molho da casa", "Brioche"],
    category: "burger",
  },
  {
    id: "menfis-chicken",
    name: "Menfi's Chicken",
    eyebrow: "Frango crocante",
    desc: "Filé de frango empanado crocante, queijo, alface e molho especial no pão macio.",
    price: 24.9,
    originalPrice: 29.9,
    image: "/MenfisChicken.jpg",
    tags: ["Frango", "Crocante", "Molho especial"],
    category: "burger",
  },
  {
    id: "menfis-bacon",
    name: "Menfi's Bacon",
    eyebrow: "Bacon crocante",
    desc: "Burger suculento, queijo derretido, bacon crocante, cebola caramelizada e maionese Menfi's.",
    price: 27.9,
    originalPrice: 34.9,
    image: "/MENFISBACON.jpg",
    tags: ["100g", "Bacon", "Brioche"],
    category: "burger",
  },
  {
    id: "double-burger",
    name: "Double Menfi's",
    eyebrow: "Mais carne",
    desc: "Dois burgers suculentos, queijo derretido e cebola caramelizada no brioche dourado.",
    price: 29.9,
    originalPrice: 37.9,
    image: burgerPhoto,
    tags: ["Double", "Mais suculento", "Brioche"],
    category: "burger",
  },
  {
    id: "double-menfis-chicken",
    name: "Double Menfi's Chicken",
    eyebrow: "Mais frango",
    desc: "Dois filés de frango empanado crocante, queijo, alface e molho especial no pão macio.",
    price: 32.9,
    originalPrice: 40.9,
    image: "/MenfisChicken.jpg",
    tags: ["Double", "Frango", "Crocante"],
    category: "burger",
  },
  {
    id: "double-menfis-bacon",
    name: "Double Menfi's Bacon",
    eyebrow: "Double com bacon",
    desc: "Dois burgers suculentos, queijo derretido, bacon crocante, cebola caramelizada e maionese Menfi's.",
    price: 35.9,
    originalPrice: 44.9,
    image: "/MENFISBACON.jpg",
    tags: ["Double", "Bacon", "Brioche"],
    category: "burger",
  },
  {
    id: "combo",
    name: "Combo Menfi's",
    eyebrow: "Pedido completo",
    desc: "Menfi's Burger, batata crocante e bebida gelada: o pedido completo para matar a fome.",
    price: 34.9,
    originalPrice: 44.9,
    image: burgerPhoto,
    tags: ["Burger", "Batata", "Refri"],
    category: "combo",
  },
  {
    id: "double-combo",
    name: " Combo Double Menfi's",
    eyebrow: "Pedido completo",
    desc: "Double Menfi's, batata crocante e bebida gelada para uma fome de respeito.",
    price: 42.9,
    originalPrice: 54.9,
    image: burgerPhoto,
    tags: ["Double", "Batata", "Refri"],
    category: "combo",
  },
  {
    id: "combo2",
    name: "Super Combo Menfi's",
    eyebrow: "Para dividir",
    desc: "Dois burgers, duas bebidas geladas e batata crocante para dividir.",
    price: 59.9,
    originalPrice: 74.9,
    image: burgerPhoto,
    tags: ["2 pessoas", "Mais vendido", "Economia"],
    category: "combo",
    highlight: true,
  },
  {
    id: "chicken-combo",
    name: "Combo Menfi's Chicken",
    eyebrow: "Pedido completo",
    desc: "Menfi's Chicken, batata crocante e bebida gelada.",
    price: 38.9,
    originalPrice: 48.9,
    image: "/MenfisChicken.jpg",
    tags: ["Chicken", "Batata", "Refri"],
    category: "combo",
  },
  {
    id: "double-chicken-combo",
    name: "Combo Double Menfi's Chicken",
    eyebrow: "Pedido completo",
    desc: "Double Menfi's Chicken, batata crocante e bebida gelada para uma fome de respeito.",
    price: 46.9,
    originalPrice: 58.9,
    image: "/MenfisChicken.jpg",
    tags: ["Double", "Chicken", "Batata", "Refri"],
    category: "combo",
  },
  {
    id: "chicken-super-combo",
    name: "Super Combo Menfi's Chicken",
    eyebrow: "Para dividir",
    desc: "Dois Menfi's Chicken, duas bebidas geladas e batata crocante para dividir.",
    price: 64.9,
    originalPrice: 79.9,
    image: "/MenfisChicken.jpg",
    tags: ["2 pessoas", "Chicken", "Economia"],
    category: "combo",
    highlight: true,
  },
  {
    id: "bacon-combo",
    name: "Combo Menfi's Bacon",
    eyebrow: "Pedido completo",
    desc: "Menfi's Bacon, batata crocante e bebida gelada.",
    price: 40.9,
    originalPrice: 51.9,
    image: "/MENFISBACON.jpg",
    tags: ["Bacon", "Batata", "Refri"],
    category: "combo",
  },
  {
    id: "double-bacon-combo",
    name: "Combo Double Menfi's Bacon",
    eyebrow: "Pedido completo",
    desc: "Double Menfi's Bacon, batata crocante e bebida gelada para uma fome de respeito.",
    price: 48.9,
    originalPrice: 61.9,
    image: "/MENFISBACON.jpg",
    tags: ["Double", "Bacon", "Batata", "Refri"],
    category: "combo",
  },
  {
    id: "bacon-super-combo",
    name: "Super Combo Menfi's Bacon",
    eyebrow: "Para dividir",
    desc: "Dois Menfi's Bacon, duas bebidas geladas e batata crocante para dividir.",
    price: 71.9,
    originalPrice: 89.9,
    image: "/MENFISBACON.jpg",
    tags: ["2 pessoas", "Bacon", "Economia"],
    category: "combo",
    highlight: true,
  },
  {
    id: "batata",
    name: "Batata Frita",
    eyebrow: "Acompanhamento",
    desc: "Porção 250g crocante, finalizada quente para acompanhar o burger.",
    price: 15.9,
    image: friesPhoto,
    tags: ["250g", "Crocante"],
    category: "extra",
  },
  {
    id: "extra-queijo",
    name: "Extra Queijo",
    eyebrow: "Adicional",
    desc: "Camada extra de queijo derretido no burger.",
    price: 2,
    image: "/queijo.jpg",
    tags: ["Derretido", "Cremoso"],
    category: "extra",
  },
  {
    id: "extra-ovo",
    name: "Ovo",
    eyebrow: "Adicional",
    desc: "Ovo preparado para completar o burger.",
    price: 2.5,
    image: "/ovo.jpg",
    tags: ["Adicional", "Quente"],
    category: "extra",
  },
  {
    id: "extra-maionese-barbecue",
    name: "Maionese Barbecue",
    eyebrow: "Adicional",
    desc: "Porção extra de maionese barbecue.",
    price: 2,
    image: "/EXTRAS/MaioneseBarbecue.jpg",
    tags: ["Maionese", "Barbecue"],
    category: "extra",
  },
  {
    id: "extra-maionese-alho-frito",
    name: "Maionese Alho Frito",
    eyebrow: "Adicional",
    desc: "Porção extra de maionese alho frito.",
    price: 2,
    image: "/EXTRAS/MaionseAlhoFrito.jpg",
    tags: ["Maionese", "Alho frito"],
    category: "extra",
  },
  {
    id: "coca-zero",
    name: "Coca-Cola Zero",
    eyebrow: "Bebida",
    desc: "Refrigerante zero gelado para acompanhar o pedido.",
    price: 8.9,
    image: "/EXTRAS/cocazero.jpg",
    tags: ["Zero", "Gelada"],
    category: "bebida",
  },
  {
    id: "guarana-zero",
    name: "Guaraná Zero",
    eyebrow: "Bebida",
    desc: "Guaraná zero gelado para acompanhar o pedido.",
    price: 8.9,
    image: "/EXTRAS/Gurarana.jpg",
    tags: ["Zero", "Gelada"],
    category: "bebida",
  },
  {
    id: "agua-com-gas",
    name: "Água com gás",
    eyebrow: "Bebida",
    desc: "Água com gás gelada.",
    price: 5.9,
    image: "/EXTRAS/aguaComGas.png",
    tags: ["Com gás", "Gelada"],
    category: "bebida",
  },
];
