import { MenuItem } from "./types";
import friesPhoto from "@/imports/image-20.png";

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "burger",
    name: "Menfi's Burger",
    eyebrow: "Clássico da casa",
    desc: "Brioche dourado, carne Menfi's 100g, queijo derretido, cebola caramelizada e maionese Menfi's.",
    price: 21.9,
    originalPrice: 25.9,
    image: "/menu/menfisburguer.png",
    tags: ["100g", "Molho da casa", "Brioche"],
    category: "burger",
  },
  {
    id: "double-burger",
    name: "BIG Menfi's",
    eyebrow: "Mais carne",
    desc: "Um hambúrguer com duas carnes bovinas de 100g (200g no total), queijo derretido e cebola caramelizada no brioche dourado.",
    price: 29.9,
    originalPrice: 39.9,
    image: "/menu/Double menfis.png",
    tags: ["2 carnes • 200g", "Mais suculento", "Brioche"],
    category: "burger",
  },
  {
    id: "menfis-chicken",
    name: "Menfi's Chicken",
    eyebrow: "Frango crocante",
    desc: "Filé de frango empanado crocante 120g, queijo, alface e molho especial no pão macio.",
    price: 24.9,
    originalPrice: 29.9,
    image: "/menu/CHICKEN.png",
    tags: ["120g", "Crocante", "Molho especial"],
    category: "burger",
  },
  {
    id: "double-menfis-chicken",
    name: "BIG Menfi's Chicken",
    eyebrow: "Mais frango",
    desc: "Um hambúrguer com dois filés de frango de 120g (240g no total), queijo, alface e molho especial no pão macio.",
    price: 32.9,
    originalPrice: 45.9,
    image: "/menu/DOUBLECHICKEN.png",
    tags: ["2 filés • 240g", "Frango", "Crocante"],
    category: "burger",
  },
  {
    id: "menfis-bacon",
    name: "Menfi's Bacon",
    eyebrow: "Bacon crocante",
    desc: "Burger de 100g, 40g de bacon crocante, queijo derretido, cebola caramelizada e maionese Menfi's.",
    price: 27.9,
    originalPrice: 34.9,
    image: "/menu/BACON.png",
    tags: ["Burger 100g", "40g bacon", "Brioche"],
    category: "burger",
  },
  {
    id: "double-menfis-bacon",
    name: "BIG Menfi's Bacon",
    eyebrow: "BIG com bacon",
    desc: "Um hambúrguer com duas carnes bovinas de 100g (200g no total), 40g de bacon crocante, queijo derretido, cebola caramelizada e maionese Menfi's.",
    price: 35.9,
    originalPrice: 47.9,
    image: "/menu/DOUBLEBACON.png",
    tags: ["2 carnes • 200g", "40g bacon", "Brioche"],
    category: "burger",
  },
  {
    id: "combo",
    name: "Combo Menfi's",
    eyebrow: "Pedido completo",
    desc: "Menfi's Burger com burger de 100g, batata 100g e bebida gelada.",
    price: 34.9,
    originalPrice: 44.9,
    image: "/menu/combomenfis.png",
    tags: ["Burger 100g", "Batata 100g", "Refri"],
    category: "combo",
  },
  {
    id: "double-combo",
    name: "Combo BIG Menfi's",
    eyebrow: "Pedido completo",
    desc: "Um hambúrguer com duas carnes bovinas de 100g (200g no total), batata 100g e bebida.",
    price: 42.9,
    originalPrice: 58.9,
    image: "/menu/combodoublemenfi.png",
    tags: ["2 carnes • 200g", "Batata 100g", "Refri"],
    category: "combo",
  },
  {
    id: "combo2",
    name: "Super Combo Menfi's",
    eyebrow: "Para dividir",
    desc: "Dois Menfi's Burger com burger de 100g, batata 200g e duas bebidas geladas.",
    price: 59.9,
    originalPrice: 79.9,
    image: "/menu/supercombomnfis.png",
    tags: ["2 burgers 100g", "Batata 200g", "2 refris"],
    category: "combo",
    highlight: true,
  },
  {
    id: "chicken-combo",
    name: "Combo Menfi's Chicken",
    eyebrow: "Pedido completo",
    desc: "Menfi's Chicken com filé 120g, batata 100g e bebida gelada.",
    price: 38.9,
    originalPrice: 51.9,
    image: "/menu/COMBOCHICKEN.png",
    tags: ["120g", "Batata 100g", "Refri"],
    category: "combo",
  },
  {
    id: "double-chicken-combo",
    name: "Combo BIG Menfi's Chicken",
    eyebrow: "Pedido completo",
    desc: "Um hambúrguer com dois filés de frango de 120g (240g no total), batata 100g e bebida.",
    price: 46.9,
    originalPrice: 66.9,
    image: "/menu/COMBODOUBLECHICKEN.png",
    tags: ["2 filés • 240g", "Batata 100g", "Refri"],
    category: "combo",
  },
  {
    id: "chicken-super-combo",
    name: "Super Combo Menfi's Chicken",
    eyebrow: "Para dividir",
    desc: "Dois Menfi's Chicken com filé 120g, batata 200g e duas bebidas geladas.",
    price: 64.9,
    originalPrice: 86.9,
    image: "/menu/SUPERCOMBOCHICKEN.png",
    tags: ["2 chickens 120g", "Batata 200g", "2 refris"],
    category: "combo",
    highlight: true,
  },
  {
    id: "bacon-combo",
    name: "Combo Menfi's Bacon",
    eyebrow: "Pedido completo",
    desc: "Menfi's Bacon com burger de 100g, 40g de bacon, batata 100g e bebida gelada.",
    price: 40.9,
    originalPrice: 54.9,
    image: "/menu/BACONCOMBO.png",
    tags: ["Burger 100g", "40g bacon", "Batata 100g"],
    category: "combo",
  },
  {
    id: "double-bacon-combo",
    name: "Combo BIG Menfi's Bacon",
    eyebrow: "Pedido completo",
    desc: "Um hambúrguer com duas carnes bovinas de 100g (200g no total), 40g de bacon, batata 100g e bebida.",
    price: 48.9,
    originalPrice: 69.9,
    image: "/menu/DOUBLEBACONCOMBO.png",
    tags: ["2 carnes • 200g", "40g bacon", "Batata 100g"],
    category: "combo",
  },
  {
    id: "bacon-super-combo",
    name: "Super Combo Menfi's Bacon",
    eyebrow: "Para dividir",
    desc: "Dois Menfi's Bacon com burger de 100g e 40g de bacon cada, batata 200g e duas bebidas geladas.",
    price: 71.9,
    originalPrice: 108.9,
    image: "/menu/SUPERCOMBOBACON.png",
    tags: ["2 burgers 100g", "40g bacon cada", "Batata 200g"],
    category: "combo",
    highlight: true,
  },
  {
    id: "batata",
    name: "Batata Frita",
    eyebrow: "Acompanhamento",
    desc: "Porção 250g crocante, finalizada quente para acompanhar o burger.",
    price: 15.9,
    image: friesPhoto,
    tags: ["250g", "Crocante"],
    category: "extra",
  },
  {
    id: "extra-queijo",
    name: "Extra Queijo",
    eyebrow: "Adicional",
    desc: "Camada extra de queijo derretido no burger.",
    price: 2,
    image: "/queijo.jpg",
    tags: ["Derretido", "Cremoso"],
    category: "extra",
  },
  {
    id: "extra-ovo",
    name: "Ovo",
    eyebrow: "Adicional",
    desc: "Ovo preparado para completar o burger.",
    price: 2.5,
    image: "/ovo.jpg",
    tags: ["Adicional", "Quente"],
    category: "extra",
  },
  {
    id: "extra-maionese-barbecue",
    name: "Maionese Barbecue",
    eyebrow: "Adicional",
    desc: "Porção extra de maionese barbecue.",
    price: 2,
    image: "/EXTRAS/MaioneseBarbecue.jpg",
    tags: ["Maionese", "Barbecue"],
    category: "extra",
  },
  {
    id: "extra-maionese-alho-frito",
    name: "Maionese Alho Frito",
    eyebrow: "Adicional",
    desc: "Porção extra de maionese alho frito.",
    price: 2,
    image: "/EXTRAS/MaionseAlhoFrito.jpg",
    tags: ["Maionese", "Alho frito"],
    category: "extra",
  },
  {
    id: "coca-zero",
    name: "Coca-Cola Zero",
    eyebrow: "Bebida",
    desc: "Refrigerante zero gelado para acompanhar o pedido.",
    price: 8.9,
    image: "/EXTRAS/cocazero.jpg",
    tags: ["Zero", "Gelada"],
    category: "bebida",
  },
  {
    id: "guarana-zero",
    name: "Guaraná Zero",
    eyebrow: "Bebida",
    desc: "Guaraná zero gelado para acompanhar o pedido.",
    price: 6.9,
    image: "/EXTRAS/Gurarana.jpg",
    tags: ["Zero", "Gelada"],
    category: "bebida",
  },
  {
    id: "agua-com-gas",
    name: "Água com gás",
    eyebrow: "Bebida",
    desc: "Água com gás gelada.",
    price: 5.9,
    image: "/EXTRAS/aguaComGas.png",
    tags: ["Com gás", "Gelada"],
    category: "bebida",
  },
];
